apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-guestbook-issuer
  namespace: guestbook
spec:
  acme:
    email: theo.vuillaume@he-arc.ch # <--- CHANGE THIS
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-guestbook-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: traefik
